### ISSUE TITLE
Regarding eval_numerical_gradient_array

### ISSUE THREAD

**Issue by balaji-ch** [mantasu/cs231n#14]
In the affine Affine layer: backward section of assignment1/two_layer_net.ipynb why are we multiplying dout which is some random array?

```python
np.random.seed(231)
x = np.random.randn(10, 2, 3)
w = np.random.randn(6, 5)
b = np.random.randn(5)
dout = np.random.randn(10, 5)

dx_num = eval_numerical_gradient_array(lambda x: affine_forward(x, w, b)[0], x, dout)
dw_num = eval_numerical_gradient_array(lambda w: affine_forward(x, w, b)[0], w, dout)
db_num = eval_numerical_gradient_array(lambda b: affine_forward(x, w, b)[0], b, dout)
```

**Comment by balaji-ch** [comment]
sorry got it... in the next lines it is used to compare against numerical gradients.

**Comment by mantasu** [comment]
Yeah, just to check if `affine_backward` works

**Comment by balaji-ch** [comment]
Still I am confused.
```python
dx_num = eval_numerical_gradient_array(lambda x: affine_forward(x, w, b)[0], x, dout)
```
```python
affine_forward(x, w, b)[0]
```
calculates Z. (i.e., X@W + b)  which gets passed to out layer.
dimensions 
X = (10, 6) effectively
W = (6, 5)
b = (5)
Z = (10, 5)

dL/dX = dL/dz . dz/dx T.
(dimensions (10,6)   (10,5) (6,5) )

Assuming that dL/dz is the dout, Then why in the eval_numerical_gradient_array dout is element wise multiplied with dz/dx ?

**Comment by mantasu** [comment]
I'm not sure what you mean, but `eval_numerical_gradient_array` is already given and it simply computes gradients with finite differences. It computes it correctly in an iterative manner using broadcasting - elementwise _full_ matrix multiplication would not be correct or even possible due to different shapes. Regardless, we don't really need to check `eval_numerical_gradient_array` - it should just be used as a tool to verify our analytical solution.

**Comment by mantasu** [comment]
Yeah, it might be a bit tricky to see. As I mentioned, this is an iterative computation that uses broadcasting between a vector and a matrix to simulate dot product<sup>1</sup>.

Easiest way to understand I think would be to run debugging and monitor the shapes in real-time. However, again, since this is not part of the main assignment, I would suggest coming back to this after completing all the tasks as it will be much clearer when you're more familiar with numpy!

<sup>
[1] I could be mistaken as I haven't looked in detail
</sup>
